### ISSUE TITLE
mai trebuie un /reports in url

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs19.homework#2]
https://github.com/cezarhre/curs19.homework/blob/46cec4925ec5e71e82c09aa9a8a74a83aba75d7b/src/main/java/ro/fasttrackit/curs19/homework/Budget/BudgetController.java#L39

**Comment by cezarhre** [comment]
Am facut prima data cu reports (dupa cum se vede la initial comit) dar era eroare...
