### ISSUE TITLE
puteai folosi Double si atunci aveai si aici null. Practic tu ai eliminat posibilitatea sa fie minAmount 0

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs19.homework#3]
https://github.com/cezarhre/curs19.homework/blob/46cec4925ec5e71e82c09aa9a8a74a83aba75d7b/src/main/java/ro/fasttrackit/curs19/homework/Budget/BudgetService.java#L23

**Comment by cezarhre** [comment]
Unde sa pun Double?

**Comment by cezarhre** [comment]
adica Double minAmount in loc de double minAmount?
