### ISSUE TITLE
ai facut cum am scris initial cu suma.. e ok.. poti face si cu lista

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs19.homework#4]
https://github.com/cezarhre/curs19.homework/blob/46cec4925ec5e71e82c09aa9a8a74a83aba75d7b/src/main/java/ro/fasttrackit/curs19/homework/Budget/BudgetService.java#L83

**Comment by cezarhre** [comment]
Am facut si cu lista

**Comment by cezarhre** [comment]
Dar nu resusesc sa o afisez pe web... nu stiu exact cum sa scriu path-ul imi da eraore
